---
name: WWW-PAUSE-RecentUploads
version: 0.03
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: get the list of the recent uploads to PAUSE
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  HTML::TokeParser::Simple: 3.15
  LWP::UserAgent: 2.036
build_requires:
  Test::More: 0
provides:
  WWW::PAUSE::RecentUploads:
    file: lib/WWW/PAUSE/RecentUploads.pm
    version: 0.03
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
